### ISSUE TITLE
How are controllers loaded?

### ISSUE THREAD

**Issue by larskarbo** [pencilblue/pencilblue#1004]
How does pencilblue know about my controllers? E.g how could I make all request go through `index.js` in my plugin?

The routes to controllers in the pencilblue plugin is located at `pencilblue/includes/routes.js` but this file is loaded through a hardcoded function in `include\http\request_handler.js
`

````
RequestHandler.CORE_ROUTES = require(path.join(pb.config.docRoot, '/plugins/pencilblue/include/routes.js'))(pb);
````

**Comment by n1ru4l** [comment]
https://github.com/pencilblue/pencilblue/wiki/Quickstart:-Controllers#registering-routes

**Comment by brianhyder** [comment]
In your particular use case if you wanted to make all requests in your plugin go through the ```plugins/pencilblue/controllers/index.js``` file (which is deprecated, just FYI) then you would want to re-register the route directly with the request handler.  This sample pseudo code can be called from within your plugin's onStartupWithContext function in its main module file.

```
var routeDescriptor = {
            method: 'get',
            path: '/my/other/path',
            access_level: pb.SecurityService.ACCESS_USER,
            auth_required: false,
            controller: path.join(pb.config.docRoot, 'plugins', 'pencilblue', 'controllers', 'blog.js'),
            content_type: 'text/html',
            localization: true
        };
pb.RequestHandler.registerRoute(routeDescriptor, 'myPluginUid', context.site);
```

You can do the above for each additional route that you want to flow through that controller.  NOTE: you may have to require the ```path``` module in your file in order to use the ```path.join``` function.  

Let us know if there is anything else that we can clarify for you.

**Comment by larskarbo** [comment]
What I really meant is how PencilBlue discovers my controllers. But I found out that it iterates and finds all files in the `controllers` directory. I found out by using random names like `12345.js` for my controllers and they worked.
