### ISSUE TITLE
Possibly to remove "/page" section of the page url?

### ISSUE THREAD

**Issue by dtaburetkin** [pencilblue/pencilblue#1032]
How to make a page with the root url?
i.e. site/pagename, without /page/.

**Comment by brianhyder** [comment]
There is no way to change the prefix for pages.  This is because of the complexity of syncing routes for pages across a cluster of nodes without having to make a database call on each request.  You have a couple of options:

1. Create a custom controller and template with the content inside of the template.
2. Create a custom controller that loads the page and renders it using the PageService.  Then pass that content into a generic template that renders it.  The controller could then register itself for the route of the page.

**Comment by dtaburetkin** [comment]
ok, thanks.

**Comment by yasirrafiq33** [comment]
@brianhyder,
In pencilblue there is a option to import wordpress blog/site. If we import word-press blog then what about the wordpress theme?

**Comment by yasirrafiq33** [comment]
@brianhyder @blakecallens @dtaburetkin @tic2000 @mhussa 

The example mention on web-site (http://www.exitevent.com/) not showing any prefix (/page).Can you please suggest any thing about this issue I really stuck in this issue.
