### ISSUE TITLE
Content page get struck on adding html

### ISSUE THREAD

**Issue by Jobbyr** [pencilblue/pencilblue#1035]
After Adding the html code in wysiwyg field,the page get struck, somehow I am able to save but if I reopen the page I cant see anything in the content area.Here I am attaching the code.

PencilBlue Version: 0.5.1

Node.js Version: v0.10.44

Environment Description: ubuntu 15.10

![struck1](https://cloud.githubusercontent.com/assets/18713830/15156834/712675de-1706-11e6-845c-af804228311d.jpg)
[test.txt](https://github.com/pencilblue/pencilblue/files/257805/test.txt)

**Comment by Jobbyr** [comment]
Kindly Reply.

**Comment by blakecallens** [comment]
My guess is that you injected some JavaScript into the article. @brianhyder?

**Comment by Jobbyr** [comment]
Is there a way that I can have a skype chat with you.To clarify more.Really messed up.

**Comment by Jobbyr** [comment]
My Id  jins.sus

**Comment by blakecallens** [comment]
@Jobbyr, the issue is most likely that you have added multiple MBs worth of HTML into the wysiwyg and JS can't process that. As @brianhyder recommended in #1029, you should break this content up. Multiple MBs of HTML is *way* too much.

We suggest deleting the page in the admin section and building a custom page with multiple sets of input. We will not be addressing this issue, as it is only reproducible through impractical means.
