### ISSUE TITLE
debugging pencilblue

### ISSUE THREAD

**Issue by awb99** [pencilblue/pencilblue#1045]
**Description:**
It seems to be impossible to debug the node.js pencilblue.js app. I tried  different debuggers, and none works. Perhaps it has to do with that it fires off worker processes?

nodespector:
https://github.com/node-inspector/node-inspector
node-debug pencilblue.js
website does not run at all.

devtool
npm install devtool -g
devtool node pencilblue.js
webite is running; however no breakpoint can be triggerd

**Comment by brianhyder** [comment]
Take a look at this:
https://pencilblue.org/article/debugging-quickstart

I haven't used node-inspector in awhile but I suspect it has to do with the configuration you have.  By default, PB attempts to scale out across your machine by using the ```cluster``` module.  When attempting to debug you must disable this feature because it uses multiple processes (node.js design decision not a PB decision.  Node doesn't have threads).  Let us know if that doesn't solve the issue for you.

**Comment by brianhyder** [comment]
Side note:  I personally use webstorm because it has built in support.  I've also used Visual Code to debug node apps with success.

**Comment by awb99** [comment]
@brianhyder Your tip worked! Just set cluster self managed to false, and it works like charm

**Comment by awb99** [comment]
@brianhyder 1000 thanks!
