### ISSUE TITLE
building custom routes and pages with sub-templates

### ISSUE THREAD

**Issue by Jobbyr** [pencilblue/pencilblue#1053]
Is there any tutorial or link for building custom routes and pages with sub-templates

Environment Description: Ubuntu 15.10

**Comment by brianhyder** [comment]
Take a look at the sample plugin that comes with each distribution of
pencilblue. Additionally, there is our wiki which is a great source of
information.

https://github.com/pencilblue/pencilblue/wiki/Quickstart:-Developing-Themes

Is there any tutorial or link for building custom routes and pages with
sub-templates

Environment Description: Ubuntu 15.10

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/pencilblue/pencilblue/issues/1053>
