### ISSUE TITLE
SEO meta_thumbnail never gets populated when viewing article.

### ISSUE THREAD

**Issue by dackyD** [pencilblue/pencilblue#1058]
**Description:**
<meta property="og:image" content="^meta_thumbnail^">
^meta_thumbnail^ will never be populated due to a function getMetaInfo in ContentObjectService returning an object instead returning the first object of an array.

/include/service/entities/content/content_object_service.js
ContentObjectService.prototype.getMetaInfo
Line: 465 
callback(err, util.isNullOrUndefined(media) ? '' : media.location);
the media returned is an array not an object. media[0].location will return the correct thumbnail data.

**Steps to Reproduce:**
Fill an article with SEO and choose a thumbnail. Inspect the article in your browser on the head section. 
<meta property="og:image" content=""> Image meta property is blank.

**Configuration Details:**

**Log Output:**

PencilBlue Version:  0.5.1

Node.js Version: 5.5.0

Environment Description: OS X 10.11.5 Google Chrome

**Comment by efleurine** [comment]
Thanks for the fix.

I saw this when I tried to share a post on Facebook. my picture as an author was there instead of the thumbnail.
(my pic was not bad but completely irrelevant to the article :)

**Comment by dackyD** [comment]
I noticed something else. It would be nice to add another property to media with a site root and location. media.location returns the media path fex. "/media/2016/5/9aacadeb-6f89-76463598864308.jpg". I verified this with facebook debugger tools and the image was invalid. It should have the site_root plus media.location.

But this is no problem at all if your media is a link then media.location will return you the complete url of the image.

**Comment by brianhyder** [comment]
@dackyD @efleurine I wanted to give you all a heads up that this has been fixed in the 0.6.0 branch.  I appreciate your patience and thank you for letting us know about the issue.

**Comment by efleurine** [comment]
Yep thanks,

One more things, when we go from one version to another I assume that the
setting are automatically invalidate because I thought just changing the
files and restart the server would make it work but it seems the setting
are read from the database and only if there are not present we would
default to the default file.

Anyway I was able to update the library too through the admin console.

thanks great work.



*Emmanuel Fleurine.*


--------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es
