### ISSUE TITLE
Error page routing and stack trace exposure

### ISSUE THREAD

**Issue by dukeofsussex** [pencilblue/pencilblue#1062]
**Description:**
I'll start this off with a public example to showcase my issue: https://pencilblue.org/woops

Even though a 404 template is present for the custom theme, it uses the default error template instead.

**Steps to Reproduce:**
- Using the default PB theme, try opening `localhost:8080/random` and you will receive the 404 page without a stack trace
- Now install the portfolio theme, set it as the active site theme, revisit that page and you will get a stack trace, even though the portfolio theme has a 404 template without the stack trace template value

Adding to this, could the stack trace be disabled in a production environment or by a config setting? I don't think it's good practice to serve internal error data to the public (not counting possible security risks due to the exposure of directories, file structures, used modules, etc.).

***PencilBlue Version:*** 0.5.1? (Mine is 0.5.1)

***Node.js Version:*** - (Mine is 4.4.3)

***Environment Description:*** Stack trace suggests Openshift (Mine is Windows)

Sorry for being so nitpicky :disappointed: Here's a piece of :cake: to cheer you up.

**Comment by brianhyder** [comment]
This was a change that was made last December. The majority of the time the template for errors was exactly the same it just displayed a different HTTP status code or page title.  We consolidated this into a generic error controller that handles the 99% usecase for us.  
https://github.com/pencilblue/pencilblue/blob/master/controllers/error_controller.js

For the 1% case we built in a mechanism to allow developers to take complete control of individual status codes.  https://github.com/pencilblue/pencilblue/blob/master/include/error/formatters/error_formatters.js#L127  Instead of providing a template developers create a controller inheriting from the error controller implementation linked to above.  This allows for providing your own template tags so any information you want can show up on the error page.  

In your particular all you want to do is create a template for a specific status code, 404.  You would need to create a controller in your active theme at: ```controllers/error/404.js```.  Inherit from the error controller and then override the ```getTemplatePath``` function to point at the template of your choice: https://github.com/pencilblue/pencilblue/blob/master/controllers/error_controller.js#L154

The portfolio theme was apparently not updated to accommodate this change.  

P.S. you can modify your config.js file in production to disable showing the stack trace:
https://github.com/pencilblue/pencilblue/blob/master/include/config.js#L212

We know how picky you devs are :)

**Comment by dukeofsussex** [comment]
Ahh, so the controller is missing, hadn't thought of that, working fine now.

Thanks Brian.

P.S.: You still might want to remove that stack trace from your website though :smile:

**Comment by brianhyder** [comment]
Good call. I'll try and handle that today.
