### ISSUE TITLE
Penciblue Issue

### ISSUE THREAD

**Issue by yasirrafiq33** [pencilblue/pencilblue#1068]
@blakecallens @tic2000 @mhussa @chonghua @ulai 
**Description:**
I make a container and put different pages in that container now I want to see url like parent/page1, parent/page2 etc.
But its show only pageID not even page name? Can you suggest me something?

One more thing when I hit the localhost:8080 then there is only menu on top I want to set a home page.
How's that possible without this(localhost:8080/page/home).

Kindly explain ^navigation^ this thing? Is this is a angular  directive or what is this and where its located in project?

Node.js Version:

Environment Description:

**Comment by brianhyder** [comment]
There is no way to change the navigation slugs due to the distributed nature of the platform.  The is expected to change when #144 is completed.

You must override the root route in your plugin in order to change home page behavior.

Items denoted as, ```^something^``` are referred to as template flags.  They can be replaced by values or functions that derive a value.  Please see the sample plugin or see our wiki for more information.
