### ISSUE TITLE
unable to save custom object with a blank peer

### ISSUE THREAD

**Issue by southbite** [pencilblue/pencilblue#1076]
**Description:**
When I create a custom object that has the "peer" field type, but is not required, an error gets raised when I try and save the object because the validation deems the blank string passed in (by default from the admin front-end) as illegal.

this issue can be solved by modifying the validation_service's isIdStr method:
```javascript
ValidationService.isIdStr = function(val, required) {
        //added the || val === ''
        if (!required && (val === null || val === undefined || val === '')) {
            return true;
        }
        else if (!util.isString(val)) {
            return false;
        }
        return ValidationService.isId(val, required);
    };
```

the service is located here: https://github.com/pencilblue/pencilblue/blob/master/include/validation/validation_service.js#L91

I have chosen not to do a PR for this, as it may be by design you are doing it?

**Steps to Reproduce:**
Create 2 custom objects, configure one to be a peer of the other, try and save the older sibling without setting its peer. 

**Configuration Details:**

**Log Output:**

PencilBlue Version: 
0.5.1
Node.js Version:
N/A
Environment Description:
N/A

**Comment by brianhyder** [comment]
@southbite Thank you for reporting.  I haven't had a chance to dive into it but I did take a quick preliminary look at things.  The validation function is behaving as intended.  What isn't clear is if the intention of the API is to represent an empty peer association through a ```null``` value or an empty string.  My theory, at the moment, is that the UI is sending an empty string to represent the empty association and not ```null``` causing the validation to fail because the string must be non-empty to represent a Mongo ObjectId.  

So now the philosophical debate, what more clearly represents an empty association?  A ```null``` value or an empty string?  I lean more toward the ```null``` value because it relates more closely to what you would expect in the DB.  This means that we'll have to update our UI or our format logic to ensure that peer values with an empty string value are converted to ```null```. 

I'll try and take a look at it tonight.
