### ISSUE TITLE
all pages aside homepage works when ssl enabled

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#1091]
"siteRoot": "https://www.ghinfocus.com",
    "sitePort": 443,
"server": {
        "ssl": {
            "enabled": true,
            "key": "ssl/privkey.pem",
            "cert": "ssl/cert.pem"
        }
    },

The above config enables ssl and all pages works except hmepage. 
I am not getting any error on server.

What is wrong?

**Comment by brianhyder** [comment]
There could be a number of things wrong.  The information you provided doesn't tell us anything.  My guess is it has to do with your homepage because we customize ours for our side and everything is working as expected.  

If you'd like to share a few more details about the version of PB, the environment you are working in, if there is a load balancer, and how you are customizing the home page through your plugin we might be able to lend some expertise.  We also don't understand by "homepage doesn't work".  What is displayed or returned from the server instead of the expected page?
