### ISSUE TITLE
How to add a new field in Article adding page

### ISSUE THREAD

**Issue by IsisPr0** [pencilblue/pencilblue#1097]
**Description:**
I need to add a new field, but data from this field are not added to the database.
What I've done:
1. Path: 
   plugins\pencilblue\templates\admin\content\article_form.html
   Code:
   <div class="form-group">
	<label>^loc_TEST_FIELD^</label>
	<input type="text" class="form-control" ng-model="article.testtext">
   </div>
2. Path:
  plugins\pencilblue\templates\angular\admin\content\article_form.html
  Code:
  articleData.draft = draft ? 1 : 0;
  /* NEW */          
  articleData.testtext = $scope.article.testtext.toString();
  /* #END NEW */			
  var media = [];

What should I do to the data from this field is added to the database?

**Steps to Reproduce:**

**Configuration Details:**

**Log Output:**

PencilBlue Version: 
0.5.1
Node.js Version:

Environment Description:

**Comment by brianhyder** [comment]
Hey @IsisPr0, great question.  Earlier versions of PB allowed this functionality.  However, what we realized was that it created a security hole to allow for any and all fields to be passed back and persisted through the API.  It also encouraged poor coding practices because the developers were not validating the input that the UI was providing.  

To correct the issue, we created the BaseObjectService.  It emits a number of events that allow for developers to hook in and allow for extra fields.  The ArticleServiceV2 utilizes this functionality.  You will need to do the following in your plugin's main module file's onStartupWithContext.

1. Subscribe to the FORMAT event. This is where you will sanitize the input for custom field you would like to add
2. Subscribe to the MERGE event.  This is where you will merge the value provided by the incoming request into the object to be persisted
3. subscribe to the VALIDATE event.  This is where you will ensure that the field meets any requirements (required, length, format, etc.).

Example:
https://github.com/pencilblue/pencilblue/blob/master/plugins/sample/services/book_service.js#L301
In the above example you will need to replace ```TYPE``` with ```article``` and provide your own handlers.  However, the example does show the parameters available and a general guideline for implementation.

This will allow you to persist the new field and ensure that it is not compromised.
