### ISSUE TITLE
Testing site on mobile without enabling multisite

### ISSUE THREAD

**Issue by larskarbo** [pencilblue/pencilblue#1107]
When trying to access the site over LAN, I am not allowed because I use the IP (192.168...) instead of localhost.

I tried setting up the site in multi site mode, but it should be an easier way.

**Comment by brianhyder** [comment]
You should be able to set your ```siteRoot``` to something like: ```http://192.168.0.100:8080``` (whatever your laptop's IP is) and run your site.  If you can't then it is possible that there is a firewall issue.

**Comment by brianhyder** [comment]
You can also use Chrome's "Device Toolbar" to simulate different screen sizes

**Comment by larskarbo** [comment]
I know that I can change the siteRoot, but I kind of hoped there was a better less hacky way. It makes it hard to test on mobile and laptop at the same time.

**Comment by brianhyder** [comment]
I'm having a hard time understanding why that is hacky.  Maybe I am missing something.  You should have an environment specific config.js file at the root of your project (that is never committed because it is local development).  Developing locally changing your configuration means a change in a single file that doesn't require changing code in the platform or your plugin.  The only case where this approach does become problematic is if you are trying to test multi-site on mobile.  Is that what you are trying to do?
