### ISSUE TITLE
A have a cuestion about dragControlListeners

### ISSUE THREAD

**Issue by ceballos59** [pencilblue/pencilblue#1124]
I would like to capture the drag event when I move an object from selected to unselected media in media_form.html. I tried as follows, but did not work: 

$scope.dragControlListeners = {
    itemMoved: function (event) { //Do what you want },
};

How I could capture that event?

**Comment by blakecallens** [comment]
The draggable select elements (media, sections, tabs) have their own controllers. That's how we bring them into pages with server side templating. Since they're in a sub scope of the main controller of the page, they can still be used in the greater scope.

What you would want to do in this instance is override ```^tmp_angular=admin=elements=inline_media^``` with a duplicate template from your plugin, that has the event listeners in it.
