### ISSUE TITLE
in admin console, I cannot edit site settings

### ISSUE THREAD

**Issue by VampireDaniel** [pencilblue/pencilblue#1129]
Hi man, I got an issue, please have a look, Thanks a lot...

**Description:**
I have created the empty config.json.

![12](https://cloud.githubusercontent.com/assets/12490709/17960571/78c58ab0-6ad9-11e6-839f-93a9d4264e7a.png)

**Steps to Reproduce:**

**Configuration Details:**

**Log Output:**

PencilBlue Version: 
0.6.0

Node.js Version:
4.5.0

Environment Description:

**Comment by brianhyder** [comment]
The site settings view you reference in your screenshot is readonly. The reason is because if those settings changed it would require a server restart for every server in the cluster. 

The config.js file allows for building out configurations (site wide settings)  from hard coded values as well as deriving them from environment or command line arguments. The afore mentioned view is simply there to allow developers and operations teams the ability to verify configurations.
