### ISSUE TITLE
Questions about robot.txt and redirect 301

### ISSUE THREAD

**Issue by webdesus** [pencilblue/pencilblue#1150]
What do you think about edit robot.txt and redirect path in inside Admin UI? I can make it. I think this functional need inside core.

**Comment by brianhyder** [comment]
I really like the idea because I think it is something that most implementations will need.  However, until we release a 1.0 version where we will have breaking changes it isn't something that we will want to maintain over the course of the next few months.  I think this is a perfect candidate for a plugin and I would strongly encourage you to submit it to our plugin repo.
https://pencilblue.org/plugins/submit
