### ISSUE TITLE
Question about error_success code

### ISSUE THREAD

**Issue by webdesus** [pencilblue/pencilblue#1154]
I understand correctly [this is](https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/templates/admin/elements/error_success.html#L1) misprint. I not found no code which write inside data. And this [file](https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/templates/angular/admin/elements/error_success.html) I should using always in my angular code? Or maybe instead misprint must be link template to this file?

**Comment by brianhyder** [comment]
Not a typo.  This is an older pattern that we used to inject in the alert boxes that provide "saved successfully" or "failed to save" messages.  It was used only with traditional form posts so that we could show the same view with the error messages.  We are moving away from traditional form posts and leveraging APIs instead for a consistent feel.  

Aside from that I'll provide a basic explanation of how it worked.  The HTML template would contain ```^error_success^```.  In the BaseController a flag handler was registered with the TemplateService so that when the ```^error_success^``` flag was found it would be replaced with HTML if there was an ```error``` or ```success``` property available in the session object.
