### ISSUE TITLE
create an upgrade guide or at least some upgrade examples

### ISSUE THREAD

**Issue by v3rt1go** [pencilblue/pencilblue#1164]
I'm struggling with upgrading from an older installation running on 0.4.0 to version 0.7.0. An upgrade guide would be really helpful.

The particular areas that are giving me the biggest headaches are the database changes and updating the custom plugins i've wrote (theme included) to work with v0.7.0

**Comment by brianhyder** [comment]
We tried to avoid breaking changes because of the issues it creates for our users.  In v1.0 coming next year there will be no way to avoid it but we will be putting together an upgrade guide for it.  As for moving from 0.4.0 there have been a lot of improvements.  

In terms of DB structure changes I can't think of anything major other than the introduction of multi-site which *should* upgrade without issue.  I would strongly recommend taking a data dump ahead of the migration just to be safe.  

Which pieces of the custom plugins are giving you problems?  We can probably help with some examples to get things up to speed a little quicker for you

**Comment by Boncratious** [comment]
I'm hoping I don't run into the same issues as v3rt1go.  Also we're also upgrading from 0.4.0 to 0.7.0.
