### ISSUE TITLE
Issues while importing the XML.

### ISSUE THREAD

**Issue by wasifale** [pencilblue/pencilblue#1217]
Error is occuring while importing the XML using wp_import plugin. it is importing only one page per import i.e I imported the XML and one page is imported then again I import overriding the existing one, it imports 2 pages. so 13 times import 13 pages will be imported but after that it shows the following error.

Error: Validation Failure at Function.custom (/Users/wasifali/Desktop/pencilblue/include/error/error_utils.js:98:19) at Function.badRequest (/Users/wasifali/Desktop/pencilblue/include/error/error_utils.js:72:31) at Function.BaseObjectService.validationError (/Users/wasifali/Desktop/pencilblue/include/service/base_object_service.js:771:27) at /Users/wasifali/Desktop/pencilblue/include/service/base_object_service.js:535:53 at /Users/wasifali/Desktop/pencilblue/node_modules/async/lib/async.js:726:13 at /Users/wasifali/Desktop/pencilblue/node_modules/async/lib/async.js:52:16 at /Users/wasifali/Desktop/pencilblue/node_modules/async/lib/async.js:269:32 at /Users/wasifali/Desktop/pencilblue/node_modules/async/lib/async.js:44:16 at /Users/wasifali/Desktop/pencilblue/node_modules/async/lib/async.js:723:17 at /Users/wasifali/Desktop/pencilblue/node_modules/async/lib/async.js:167:37

Using default setting.
XML file is here
[XML.zip](https://github.com/pencilblue/pencilblue/files/757004/XML.zip)

**Comment by brianhyder** [comment]
Thanks for the report. We'll take a look shortly.

**Comment by brianhyder** [comment]
@wasifale I have a PR out now to correct the bug you found.  The reason it only did one page at a time was because it was calling the wrong callback.  The stack trace you saw was because one of your pages was throwing a validation error. PencilBlue, at this time, does not allow duplicate headlines for articles and pages.  I've updated the error output to now indicate the which pages are triggering the errors.  Additionally, your image embeds are relative.  The import tool cannot go fetch and download or properly reference the media without being prefixed protocol and hostname.  The import will complete successfully even without updating these but then the process becomes manual to fix the media links later.

**Comment by wasifale** [comment]
Thanks @brianhyder , it worked.
