### ISSUE TITLE
New site creation

### ISSUE THREAD

**Issue by pjindent** [pencilblue/pencilblue#1226]
**Description:**
I was able to create a site with out-of-the-box install.  I changed the db parameters.  I configured webserver nginx connect to a outside domain name and I get this message:

The host (xxxxyyy.com) has not been registered with a site. In single site mode, you must use your site root (http://localhost:8080).

Question:  I am looking to use pencilblue as a free open-source CMS for a website.  Initially something simple--a few pages. Is this the right usecase for pencilblue?  I want to use a nodejs CMS akin to Drupal.  I will host the server, etc.

**Steps to Reproduce:**

**Configuration Details:**

**Log Output:**

PencilBlue Version: 

Node.js Version:

Environment Description:

**Comment by brianhyder** [comment]
Your site root in your config.js file must contain the hostname for your
domain.

On Feb 14, 2017 6:12 PM, "pjindent" <notifications@github.com> wrote:

*Description:*
I was able to create a site with out-of-the-box install. I changed the db
parameters. I configured webserver nginx connect to a outside domain name
and I get this message:

The host (xxxxyyy.com) has not been registered with a site. In single site
mode, you must use your site root (http://localhost:8080).

Question: I am looking to use pencilblue as a free open-source CMS for a
website. Initially something simple--a few pages. Is this the right usecase
for pencilblue? I want to use a nodejs CMS akin to Drupal. I will host the
server, etc.

*Steps to Reproduce:*

*Configuration Details:*

*Log Output:*

PencilBlue Version:

Node.js Version:

Environment Description:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pencilblue/pencilblue/issues/1226>, or mute the thread
