### ISSUE TITLE
WYSIWYG adding media is working incorrectly

### ISSUE THREAD

**Issue by vunguyen-it** [pencilblue/pencilblue#1234]
**Description:**
There are 2 issue with the WYSIWYG editor that I have got:
- The media (image) is not inserted to the WYSIWYG content when I insert a media  by media selecting dialog.
- The content of WYSIWYG has been changed automatically and i lose my content after i switched between WYSIWYG view mode and HTML view mode. The issue is happened when there is a inline media in the editor content.

**Steps to Reproduce:**
- Login to admin dashboad
- Go to edit the content of a page (or create new page)
- Open media selecting dialog then select an image then click insert (First issue here, the image will not inserted to the WYSIWYG, I have to try open the media selecting dialog again then click insert without touching to the image radio)
- Continue adding new line and entering some text after the image
- Switch editor view to HTML view mode then switch back to WYSIWYG view mode without modifying any thing.
- Now the image is duplicated and the texts I entered after the image is removed.

PencilBlue Version: 0.8

Node.js Version: v5.12.0

Environment Description:
Mac OS v10.11.5

**Comment by blakecallens** [comment]
@tuanvu89 does it work if you first type things into the wysiwyg?

**Comment by tuanvu89** [comment]
@blakecallens It doesn't work if I type things first into the wysiwyg. I encountered those issues every time and no matter what I have typed before. Here is my screen recorded https://www.dropbox.com/s/oqabl2i5tgdx9vb/penciblue_editor_issue.mov?dl=0

**Comment by blakecallens** [comment]
Thanks, @tuanvu89. It looks like the media is being added the first time, but not rendering the preview in the wysiwyg. I think that's why when you switch back from HTML it renders twice (you're adding it twice, even though it doesn't show the first time).

Are there any errors in the JS console when you add the first time?

**Comment by tuanvu89** [comment]
Hi @blakecallens, there are no errors in the JS console when I reproduce the issue. I think it not about rendering because I have tried switching the view to the HTML view in the first time and I don't see any media shortcode there. 
If I reopen the media selector and select another media item to insert again then it will be not inserted. I was noted that the cursor in the editor was missing when I click to any radio button in the media selector dialog, so that the editor can be not work at that time.

**Comment by dotnetjalps** [comment]
Is there any update on this? As I tried to add media on article and it's not allowing to update
