### ISSUE TITLE
Custom authentication for users.

### ISSUE THREAD

**Issue by vkomodey** [pencilblue/pencilblue#1236]
Hi! That's not an issue, just a question. I'm developing application which use pencilblue as a separate service. This service allows customers to build their own sites with authentication. Also we have login service, api service and so on. All my users are stored in separate. Login  service is required for auth operation like login, signup and so on. So we configured our pencilblue installation  in a such way, that customers can create their own sites and add different plugins for them. Some plugins required authentication. 
    Is there an easy way to do custom authentication with all routes marked with specific flag(like `player_auth: true`)?. I saw SecurityServer which provide different auth mechanisms(like UserNamePassword, token, forms), but it seems that it is responsible only for admin purposes(correct me if i'm wrong). It is very hard to understand how should i use this services by only reading code.
My thought is to create some controller/service(?), which should perform all this authentication operations and let other controllers to perform their actions if authentication was success. It is like middleware in express.js: `expressController.get('/resource', authMiddleware, getResourceMiddleware)`. Is it possible to do this?

PencilBlue Version: 
0.6

**Comment by brianhyder** [comment]
In PB 0.6.x definitely not. 0.8.x would be tour best bet. That release introduces a new router that allows for the injection of middleware. You replace or override the auth checks. 

While I know it is possible I'm not sure on level of effort. We'd definitely be interested in knowing how it goes if you scope it out.

**Comment by vkomodey** [comment]
@brianhyder thanks for response
In that case i see only 2 ways to resolve this.
* Add authentication logic to each controller which need authentication. I can move this logic to the separate service and add just one line of code to each controller. Looks like a hack:). And I Don't like this approach, because developer easily could forget to add this logic while writing plugin and it would be a disaster.
* Change version of pencilblue to 0.8 and use middlewares.
 The second one is better for us, but it seems that there is a lot of work to change version from 0.6 to 0.8. Does this versions are compatible with each other?

**Comment by brianhyder** [comment]
If you would like to try approach 1 then I would suggest create a controller that overrides the ```init``` prototype function to perform your logic then calls the super prototype's ```init``` function.  This means that code reviews are easy because you just always inherit from your custom controller.  

If you would like to try approach 2 then I would suggest that you start with a dump of a working DB use mongo_dump and mongo_restore.  This way you can continuously reset the DB to check for differences during the upgrade.  We use semantic versioning and do our best to avoid breaking changes.  The upgrade process should be as easy as updating to the latest code on our master branch and then starting the server back up.  If you run into issues, which I don't expect unless you were doing something really custom, we are available here and on gitter.im/pencilblue/pencilblue
