### ISSUE TITLE
Contact form Plugin installing error

### ISSUE THREAD

**Issue by wasifale** [pencilblue/pencilblue#1237]
Hello,
     I was using the Contact-pencilblue plugin and it was working fine but all of a sudden it stoped working and now when I'm installing it again it is showing me an error which says.

> An error occurred while attempting to complete the action: MongoError: E11000 duplicate key error index: site.plugin.$uid_1 dup key: { : "contact-pencilblue" } at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:31:11) at toError (/node_modules/mongodb/lib/utils.js:114:22) at /node_modules/mongodb/lib/collection.js:737:67 at /node_modules/mongodb-core/lib/connection/pool.js:455:18 at _combinedTickCallback (internal/process/next_tick.js:67:7) at process._tickDomainCallback (internal/process/next_tick.js:122:9)

Contact form is also disappeared.

**Comment by brianhyder** [comment]
Please file issues for plugins agains their repository.  

The error indicates that you attempted to insert a document into the plugins collection with a property ```uid```.  There is a unique index on this property for the plugins collections.  So when you attempt to insert a second document with the same ```uid``` value ("contact-pencilblue" in this case) the error is thrown.  

The issue you are running into is most likely because contact-pencilblue is not compatible in multi-site mode.

**Comment by wasifale** [comment]
I find that in plugins repositories I got the answer late so I filed it here.

So what will be the suggested solution for this problem?
