### ISSUE TITLE
Admin - Email Settings - Send Test Email Enhancement

### ISSUE THREAD

**Issue by DaveAuld** [pencilblue/pencilblue#220]
Enhancement Request:

Add a "send test message"  button/facility to the email settings page.

**Comment by nzfarmer1** [comment]
Is there a way I can test this?  My "Send(TestEmail)" button (after setting up Custom SMTP) does nothing at all - nothing in client or server. Have tried setting debug mode and watching browser console. thx.

**Comment by brianhyder** [comment]
Yes, you can test it out.  The best way would be to use Chrome and the
developer tools to step through the click action for the send button.  The
client side angular javascript that should be executing can be found here:
https://github.com/pencilblue/pencilblue/blob/aa77308bc86233c895747f9a95ca03f5ac3a1760/plugins/pencilblue/templates/angular/admin/site_settings/email.html
 I would use chrome to set break points and step through the functions to
figure out where the issue is.

On Mon, Apr 20, 2015 at 5:17 AM, Andrew McClure <notifications@github.com>
wrote:

> Is there a way I can test this? My "Send(TestEmail)" button (after setting
> up Custom SMTP) does nothing at all - nothing in client or server. Have
> tried setting debug mode and watching browser console. thx.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/issues/220#issuecomment-94402954>
> .
>



-- 
Brian P. Hyder

**Comment by HadenHiles** [comment]
Not sure if this is directly related but I am having an issue trying to use my gmail account to send emails. I get an authentication error when trying to send a test email.
```
"name":"AuthError","data":"534-5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbuwi\r\n534-5.7.14 6-dLorzslZgp541nP2mFDM2YWgmj0lH5UvN3t3vtnU8BwvMenFO5fyvRX8nnwThh1wuPLk\r\n534-5.7.14 5uBe-vvtYLcFE7lV-5DyGBbQLvX6z-o6XoRSDY8vCX-7jtST_aLtm6anV31H4NacAngHuv\r\n534-5.7.14 GgnpX4XdThEh7nCcXEiGPou6b4AVvNYckhWO6DRmi-10qV4PLbBE5ADHMvbmvfBDFwAXeg\r\n534-5.7.14 gJTzQup8V1OP0MHxhz5y0OrEjckU> Please log in via your web browser and\r\n534-5.7.14 then try again.\r\n534-5.7.14 Learn more at\r\n534 5.7.14 https://support.google.com/mail/answer/78754 63sm5749329qgl.31 - gsmtp","stage":"auth"}
```
It seems as though google is blocking my sign in attempt, how can I get around this?
Thanks

**Comment by DaveAuld** [comment]
@HadenHiles Have a look at this page...https://support.mailpoet.com/knowledgebase/sending-with-gmail-doesnt-work/

**Comment by HadenHiles** [comment]
Thanks @DaveAuld, I can confirm that this is the issue I was having.
