### ISSUE TITLE
Custom parent controller to replace PencilBlueController

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#419]
Can I define a custom parent controller to replace PencilBlueController? If so, how?

**Comment by blakecallens** [comment]
Yes, use the getAngularObjects function that came with 0.3.0, instead of the getAngularController function. Then you're going to want to change your head template to use your custom app and controller instead of the PB ones.

Look at the new admin section to see how we're creating dynamic Angular controllers as [subloaded templates](https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/templates/angular/admin/content/topics/topic_form.html).

**Comment by JahlomP** [comment]
OK, thanks
