### ISSUE TITLE
Load Media from windows SO

### ISSUE THREAD

**Issue by ivanbtrujillo** [pencilblue/pencilblue#429]
Hi, i have installed a default project of pencilblue with no changes on my local machine. The problem occurs when i try to upload media from the pencilblue admin panel. I get this error on browser console:

```
GET http://localhost:8080/api/admin/content/media/get_link?url=\media\2015\1\54b56bfb0a080a841590317d-1421175803770.jpg 400 (Bad Request)angular.js:8165 (anonymous function)angular.js:7967 tangular.js:7708 hangular.js:11100 Hangular.js:11100 Hangular.js:11186 (anonymous function)angular.js:12175 h.$evalangular.js:12004 h.$digestangular.js:12279 h.$applyangular.js:7991 gangular.js:8196 Cangular.js:8137 y.onreadystatechange
new:384 Object {message: "An invalid URL was provided", data: null, status: 400}
```
I have checked that the images are loaded into media folder but seems that the problem are the slash into URL.

http://localhost:8080/api/admin/content/media/get_link?url=\media\2015\1\54b56bfb0a080a841590317d-1421175803770.jpg

Look slash on the url that pencilblue tries to load, it seems that windows doesn't recognize it.

Thanks for support!

**Comment by blakecallens** [comment]
So it looks like the URL validation in the API call is failing, because of the backslashes in it, which is technically correct - \media\2015\... is not a valid URL. But that's the file location being returned by Windows *after the upload is successful*.

I attempted to nip this in the bud by replacing the backslashes with forward ones in the return from the upload_media API call. Just having a valid URL for the get_link call should solve this problem.

@ivanbtrujillo can you pull [branch PB429](https://github.com/pencilblue/pencilblue/tree/PB429) and see if this solves the problem?

**Comment by ivanbtrujillo** [comment]
Done! it works like a charm! Thanks Blake!

**Comment by brianhyder** [comment]
@ivanbtrujillo @blakecallens Just an FYI that I have moved the fix down a layer into the MediaService so it will take effect everywhere that handles media.  I have included the fix in the story/PB13 branch which will be merged shortly.  The fix should be included in master by tomorrow.
