### ISSUE TITLE
Will you be able to do a Chinese document of pencilblue?

### ISSUE THREAD

**Issue by janryWang** [pencilblue/pencilblue#450]

**Comment by blakecallens** [comment]
If you mean code documentation in Chinese, then unfortunately we can't, since no one on our team knows Chinese. If someone is willing to translate our current documentation, we're all for it and will help in any way we can.

If you're talking about a Chinese localization file for the admin section, then we're always looking for new language submissions.

**Comment by janryWang** [comment]
I hope that all can support Chinese, although I regret, but I am also very happy to receive your reply☺️

**Comment by blakecallens** [comment]
Take a look at our [english localization file](https://github.com/pencilblue/pencilblue/blob/master/public/localization/en-us.js). If this is professionally translated into Chinese, then we'll be happy to add it to the repository.

**Comment by janryWang** [comment]
Ok,Maybe I can try to translate it😄
