### ISSUE TITLE
Localization should default to English if keys are not available in other language

### ISSUE THREAD

**Issue by bitterulf** [pencilblue/pencilblue#508]
In the backend it is very annoying that i am forced to work with the german translation while everything i read about pencilblue is written in english and it gets even worse if i install plugins without any german translation.

And your website should also switch to english if no german translation exists.

![2015-03-27 10_36_19-pencilblue](https://cloud.githubusercontent.com/assets/6606593/6865356/37422610-d46d-11e4-8190-cd2a1fae1bc2.png)

**Comment by blakecallens** [comment]
Thanks for catching this, @bitterulf. I'll open a second feature request to add a language selection interface element for the 0.4.1 milestone. I'm going to change the title of this one to the second issue you found, since it's a full on bug.

The intended behavior is to default to English when the set language isn't available, so our site doing this is definitely a bug. @brianhyder id like to get this in to 0.4.0 if possible. If not, then it should be the first bug fix after, IMO.

**Comment by brianhyder** [comment]
I agree.  I thought we already had that in.  It is a little late in the game for 0.4.0 but will go into master next week after the release.

**Comment by brianhyder** [comment]
@bitterulf You should be able to get fall back functionality now.  You can also specify the fall back locale in the configuration.  I'm planning on addressing the other major localization issue at some point in the near future.  Hopefully, this alleviates the immediate pain.
