### ISSUE TITLE
Template failures causing 404's on resources

### ISSUE THREAD

**Issue by rainabba** [pencilblue/pencilblue#530]
I don't think it's relevant, but I've disabled the collMod calls referenced in https://github.com/pencilblue/pencilblue/issues/529 so I could try and continue to evaluate pencilblue.

Once those calls were disabled, the server did start and serve the "new admin user" page though it was styled poorly. The login page afterwards also looked pretty rough so I checked Chrome DevTools and found a bunch of 404's that appear to be due to failed parsing of pb intents which result in URLs such as:
```
http://localhost:8080/admin/%5Ejquery_validate_src%5E
```

Below is my log which includes related error such as:
```
{"level":"silly","message":"TemplateService: Failed to process flag [jquery_validate_src]","timestamp":"2015-04-04T00:30:20.407Z"}
```

 Log is attached with extension .png (too big to paste here. Just download and rename to .txt)

![pencilblue](https://cloud.githubusercontent.com/assets/553630/6990741/666ac206-da28-11e4-88f8-3925ecbfb89b.png)

**Comment by brianhyder** [comment]
It appears that your content settings weren't initialized on first startup.  Can you verify that logging into the admin section and navigating to: ```Settings => Libraries``` and then clicking save corrects your issue?

**Comment by brianhyder** [comment]
After looking at the logs I think you might have commented out a callback somewhere because the rest of the initialization output was not provided in the logs you posted.  Upon a successful startup the last line will be something like: ```2015-04-04T12:25:34.044Z - info: [1] PencilBlue: Ready to run!```.  

My best guess is that because the startup sequence did not complete the libraries settings were not initialized causing the page to be missing references to the needed js libs.

Can you check to ensure that the items that you commented out still callback appropriately?

**Comment by rainabba** [comment]
The only item I commented out was the collMod() call and I can't navigate in settings at all because of the template failures. I just pulled fresh and am going to give things another try, including the fallback to redis mentioned in the mongoDb issue.
