### ISSUE TITLE
HTML View/Edit - Insert Media Not Working

### ISSUE THREAD

**Issue by evanadams28** [pencilblue/pencilblue#558]
To reproduce: Navigate to the admin/content/pages section of the admin console. After associating some media to the page, select the 'html view' of the content section then attempt to insert media. It will not generate the div tags containing the content you wish to insert.

The workaround currently is to insert media while under the WYSIWYG view, switch to the HTML view, find the generated content then cut/paste the generated div tags where you actually want it on the page.

**Comment by blakecallens** [comment]
This is currently working as designed. The two insert buttons are designed to work only with the wysiwyg view.

Since there's confusion with intended functionality, I'm inclined to disable the buttons when you're not in the wysiwyg view.

Thoughts?

**Comment by JahlomP** [comment]
I think making it work both in WYSIWYG view and HTML view will make composing of articles easy.

**Comment by brianhyder** [comment]
I agree with Blake's idea. The reason is because the images for the media are rendered consistently when inserted via wysiwyg. Meaning, the HTML is generated on the fly when the article is rendered. If the HTML is generated it would have to be manually updated if the image renderer changed.

We could implement the functionality to pre-render the control but from that point forward the inserted media would no be recognized as associated with the article because the media directive was traded in for the rendered HTML.
