### ISSUE TITLE
Run node + pencilblue with plesk

### ISSUE THREAD

**Issue by t0t** [pencilblue/pencilblue#607]
hi, I use a traditional hosting service with my own IP and ssh access on a linux Debian machine on the cloud. It has Plesk, node installed, MongoDB, also git... 

Can you indicate any tutorial i order to make step by step Pencilblue and Node run there? I'm lost with the IP's, ports, DNS... ;(

![captura de pantalla 2015-05-15 a las 3 51 59](https://cloud.githubusercontent.com/assets/6004806/7645344/0b310b96-fab4-11e4-9ba1-ca94ec986915.png)

**Comment by blakecallens** [comment]
Plesk and Node generally don't mix well, since Node is meant to create it's own http server. We currently don't support these types of environments, because the vast majority of node users deploy their applications to cloud services.

Here's a [link](http://jxcore.com/managing-node-js-applications-with-jxcore-plesk-extension/) on hosting Node apps in Plesk with JXCore, if you still want to go this route.

**Comment by t0t** [comment]
thanks @blakecallens,

I've decided to test pencilblue on a real server with 1click-install enviroiments like Nodejs, MEAN, etc. www.digitalocean.com

Which is more appropiate to host pencilblue?. As I can understand Pencilblue runs into its own server and already makes use of mongodb, node and express (if they are previously installed on the server). I'm very confused about that... 

In other words, if I have a folder architecture for MEAN on the server, or Node, where sould I install pencilblue?
;(
