### ISSUE TITLE
Compatibility issue with Redis Labs

### ISSUE THREAD

**Issue by markbaird** [pencilblue/pencilblue#612]
Given the fact that [Redis Labs only allows one database](https://support.redislabs.com/hc/en-us/articles/202215763-Can-I-have-multiple-databases-on-my-Redis-DB-Getting-ERR-invalid-DB-index-), instead of multiple numbered databases, PencilBlue currently fails to connect successfully to Redis Labs.

I found that `redis_registration_provider.js` specifies a Redis database index of `2`, on line 46. RedisLabs only allows an index of `0`, and I found that if I change that to `0` then I seem to be able to use PencilBlue with a Redis Labs database. However I'm worried about what the implications of changing the registry database index are. Does PencilBlue need more than one Redis database in order to work correctly?

**Comment by brianhyder** [comment]
I don't think it does. If I recall correctly I selected a second database
in order to reduce the risk of locking up the instance while doing key
scans. I think o e operation calls keys xyz* to find a specific key
pattern. If this is an issue we can certainly make that a configurable
parameter or move to a single glass data are to support the new versions of
redistribution that do have moved past the deprecated instances with
multiple dbs

**Comment by markbaird** [comment]
I think your auto-correct tripped you up on that last sentence. I'm not sure what you are saying.

Also, what exactly is the minimum required setup to run multiple instances in a horizontally scaled environment? Do you just need redis or mongo configured for the registry, or do you also need specific cache settings configured under settings, templates and plugins? It looks like configuring the registry to use mongo or a shared redis instance, and then configuring `settings.use_memory = false` or possibly setting `settings.memory_timeout` to some low value would be enough?

**Comment by brianhyder** [comment]
You are correct. My apologies. swype will be the death of me one day.

The most scalable solution is to use a real redis instance for caching
(command, registry, session, plug-ins). Use memory for templates. S3 for
media. In-momory will work at scale because it uses the command service to
notify other processes when things change but we have not tested it at mass
scale.

What I meant to say was:
If this is an issue we can certainly make that a configurable parameter or
move to a single database to support the new versions of redis that have
moved past the deprecated versions that supported multiple dbs

**Comment by markbaird** [comment]
My site has been running for several days now with `REGISTRY_DB` set to `0` without issues. I think it would make sense for that to be a configuration option.
