### ISSUE TITLE
Startup fails on 2nd time

### ISSUE THREAD

**Issue by anlawande** [pencilblue/pencilblue#634]
Hi Team,

I tried installing the pencil blue node module. It's starts up the first time (with some module not found errors) but 2nd time I start it and hit the root URL, it crashes with below error.

```script
Assertion failed: cb->IsFunction(), file g:\\jenkins\\workspace\\nodejs-msi\\d73b0901\\src\\async-wrap-inl.h, line 230**  
```
I dont even have a G drive . I don't know where that file i coming from.

Every startup is preceded with module not found errors
```script
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
```

**Comment by brianhyder** [comment]
That BSON line indicates that it is the Mongo dependency failing. Most of
the time this is because the npm install errored at some point but
continued on. Please try removing the node_modules directory under your
pencilblue installation and then run npm install with your pencilblue
installation as the working directory.

Let us know if that fixes it or not. If not, could you please pass along
the version of node you are running and whether or not you used the cli to
install?

**Comment by anlawande** [comment]
Yup node-gyp error. Just went right by me. VCbuild stuff. God I hate these VCbuild packages.

**Comment by brianhyder** [comment]
Yeah, it is a pain. It is the one reason we can't deploy to azure. Glad we
could get things figured out.

**Comment by anlawande** [comment]
Unfortunately this issue is still occuring even with all modules installed successfully.

```script
Assertion failed: cb->IsFunction(), file g:\\jenkins\\workspace\\nodejs-msi\\d73b0901\\src\\async-wrap-inl.h, line 230**  
```

**Comment by brianhyder** [comment]
Are you having the issue on tour local machine or a vm?

**Comment by anlawande** [comment]
local machine win 8.1 x64.
Modules built using vs 2015

The error comes when I hit any URL after starting the server. It is uncaught and crashes the entire server

**Comment by brianhyder** [comment]
Awesome, thank you for the additional info. I have a windows 7 machine
sitting around somewhere. I'll fire or up and see if I run into any issues.

**Comment by brianhyder** [comment]
@anlawande I wanted to provide an update.  I went through a fresh install on Windows 7 machine without VS installed.  Everything ran as normal.  I'm working on getting the VS community installation downloaded and installed.  I'll retry after that and give you a heads up what I find.

**Comment by anlawande** [comment]
Thanks @brianhyder

**Comment by brianhyder** [comment]
@anlawande I installed VS 2015 and still cannot reproduce the error.  On a fresh install BSON does produce an error during the ```npm install``` even with the error PB still starts up because the BSON defaults to the pure JS implementation instead of the c++ extension.

What version of Node.js are you running?  I did find this post:
https://github.com/joyent/node/issues/7691

If you are not running Node.js 0.12.x would you performing the following:
* Upgrade to node.js 12
* delete the node_modules directory for your PB installation
* run ```npm install```
* Start PB

**Comment by anlawande** [comment]
Hey @brianhyder. Sorry for the delay. I did try a nodejs upgrade. It doesn't seem to crash now.
But earlier I was facing process hangs. But today I'm not.
Going to experiment with setting up on openshift.
I'm only concerned about the high CPU utilization. If it persists I will follow up with another issue.
