### ISSUE TITLE
URL Key check stopped working

### ISSUE THREAD

**Issue by duc-nguyen-locm** [pencilblue/pencilblue#637]
I installed build from 6/4/2015 and noticed the Check button when creating navigation has stopped working.

**Comment by brianhyder** [comment]
Confirmed as UI bug.  

1. Navigate to the admin section
2. Click "Navigation" on the left hand side
3. Click "+" to create a new nav item
4. Select "Section" as the type
5. Enter "check-me" into the URL Key field
6. Click the "Check" button

Result: Nothing happens.  No console error or UI action.  

Notes:
The button element has an "ng-click" attribute that points to a function ```validateURL('section', navItem.url)```.  However, I was unable to locate that function in the page source.  I could have missed it since no console error was thrown.  

@blakecallens can you take a look?

**Comment by blakecallens** [comment]
I'm on it.

**Comment by duc-nguyen-locm** [comment]
Thank you!
