### ISSUE TITLE
The quickstart guide has old commands

### ISSUE THREAD

**Issue by silne30** [pencilblue/pencilblue#672]
The quickstart guide has the install command for PencilBlue as `pbctrl install [directory]` but should be `pencilblue install [directory]`. Nothing major but good for consistency.

**Comment by brianhyder** [comment]
Thanks for reporting.  Both should work on a Linux based system.  We moved to ```pbctrl``` because it was causing collisions on Windows systems.  The pencilblue.js file was being recognized as an executable rather than falling back to a registered command on the path.  

Was there a particular place in the guide where ```pencilblue``` was referenced?  I was hoping I caught them all.
