### ISSUE TITLE
Having a template element named media gets that element rendered instead of images

### ISSUE THREAD

**Issue by v3rt1go** [pencilblue/pencilblue#708]
I'm working on a custom pencilblue theme, and I have one .html file under /plugin/<name>/templates/elements named media.html

I use ^tmp_elements=media^ to render this element on a page.
I've created an article that was using another layout file (not index.html which contains ^tmp_elements=media^). When adding content for the article from /admin I've associated a couple of media items with that article and inserted them in the text using the media icon in the rich text editor. This in turn creates a ^media_XXXX_XXXXXXX^ item.

While previewing the content in the rich text editor everything showed fine, but when saving the article and viewing it in the front end, the content of media.html is rendered instead of the actual image.

**Comment by blakecallens** [comment]
We'll take a look and see if we can reproduce, but in the meantime I would suggest changing the name of your element as a workaround, if you haven't already.

**Comment by v3rt1go** [comment]
Hi Blake,

Thanks for your reply. Indeed I've renamed my element and the problem was gone. 
Please let me know if you want me to send you some code or more details on how to reproduce the issue.

Meantime I've been working on a plugin that can make use of this "bug"/"feature", something on the lines of a template builder :)

Cheers!

**Comment by brianhyder** [comment]
If you wouldn't mind sending us the steps to reproduce we would greatly appreciate it.  The behavior you are describing appears to be what is expected.

We do that so that themes do not have to override all templates in order to change how a common piece of the application is rendered.  

In your particular case what is happening is that editor only relies on the media renderers to generate the preview.  When the media is rendered in an article the media rendering is placed inside of the template at ["/elements/media.html"](https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/templates/elements/media.html#L3) when the TemplateService encounters the *^media^* flag.  The template you overrode has the same relative path.  When the template service executes it sees that your theme is active so it checks to see if you have provided an implementation of the media element.  Since you have it uses that rather than the default implementation provided by the pencilblue theme.

Does that make sense or did I confuse everyone?
