### ISSUE TITLE
RBAC Framework Plugin Ideas

### ISSUE THREAD

**Issue by JuniorHaxe** [pencilblue/pencilblue#718]
I am beginning the foundation of an RBAC framework and examples for PencilBlue. 

I have an immediate requirement to make certain sections editable only by certain users, or certain access levels. Can anyone offer advice as to how requirements like this are implemented with the current release?

**Comment by blakecallens** [comment]
You can make a plugin that overrides the routes that you need to add additional permissions for and funnel them through a function that checks against your custom permission setup before passing them through to the default controller for that route.

You would do that by using ```util.inherits``` to make your custom route inherit from the default controller and then call that inherited controller if it passes custom permissions. [Here's a controller](https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/controllers/article.js#L54) from the default plugin that inherits from another one.

@brianhyder, keep me honest if I'm missing something here.

**Comment by brianhyder** [comment]
That sounds about right.  The tricky part (that we haven't accounted for yet) is dynamic role/permission sets.  Plugins must declare permission sets at install time.  You need to have a common function that can inspect a user's roles and permissions.  

You would most likely want to override the login controller so you can populate the additional (external roles/permissions) to the session so that you don't have to make additional calls for each request.

I don't think it would be terribly difficult to modify the SecurityService such that it fired a ```UserAuthenticated``` event that could be subscribed to if that turned out to be the only real way to accomplish this goal.

**Comment by JuniorHaxe** [comment]
Thanks for the suggestions. As I lack the in depth knowledge of the PB codebase still, I decided to inject a middleware component and build out the custom roles and permissions in a external directory apps. I implemented sections of the admin templates, accordingly. It would be great if we can simply offer an API and plugin into existing providers, as an endpoint to whatever internal solution is reached.
