### ISSUE TITLE
Flag naming in Media Loader proposal

### ISSUE THREAD

**Issue by evanadams28** [pencilblue/pencilblue#745]
Hey guys,

I was recently tasked with finding a method where we could both let clients upload their own media and reference it in their own templates. Currently, the media service renders to a flag of the structure: `^media_display_{mediaObjectID}/{optionalStyling}^`. This isn't very client-friendly because the object ID has no semantic value. When reading a template no one knows what the media content resolves to. I would like to propose a change that would carry more semantic value. For example, `^media_display_{fileName}^` or `^media_display_{mediaName}^` is more friendly on the eyes and carries meaning. I heard through the grapevine that you guys were re-thinking through the media and template services lately. Has this stuff come up in any discussions?

Best,
Evan Adams

**Comment by brianhyder** [comment]
It hasn't come up in any of our discussions.  We use the GUID because of the uniqueness.  The names and captions are not required to be unique.  This could create potential conflicts.  Our line of thinking is that the majority of the time the user will be generating content through the wysiwyg and will not have to deal with the embedded flag.  

Is there a specific issue that you are running into that is prompting the change request?

**Comment by evanadams28** [comment]
No, no specific issues. Just business needs. I'll be taking a different route for a solution to this if you guys aren't changing the structure of things in the upcoming changes. Thanks for the feedback, Brian!
