### ISSUE TITLE
add autoincrement field ?

### ISSUE THREAD

**Issue by jrweb247** [pencilblue/pencilblue#776]
I'm new in MEAN stack but I would be interesting to got an unique integer id for the objects, just for exemple to put on the url. _id like 560b83f27ab918ab3ec4528f are ugly for seo, maybe something like that : http://docs.mongodb.org/manual/tutorial/create-an-auto-incrementing-field/

**Comment by brianhyder** [comment]
I doubt we will ever convert our IDs to integers and here's why:

With the addition of multi-site coming in 0.5.0 we anticipate that some installations will be dealing with a large number of documents.  This does not typically scale well.  The GUIDs used by mongo solve the geo-scale issue where you need to replicate data across data-centers.  In the scenarios where you have multiple write databases in separate regions you need this to be able to allow for fast inserts.  You can guarantee there are no collisions and you don't have to consult with each DB instance to see if one of them has already used the integer.

Hopefully, that answers your questions but if there is anything we can clarify let us know.  As an aside, URLs to articles and pages also allow for referencing them by the slug.  We don't do this from the menu because we cache the menu structure.  We are targeting to update the way the menu building and storage structure works in the next couple of quarters.  At that point we anticipate to be able to reference primarily by the slug.
