### ISSUE TITLE
Enhancement Idea:  Files Assets in addition to images and videos

### ISSUE THREAD

**Issue by thcase** [pencilblue/pencilblue#780]
In looking at PencilBlue to potentially serve needs for types of small to medium sites that the organization I work for manages, one of the standard needs is to store files in addition to images and media.  Most of the time these files are PDF's.  They also could be links (like media) to other file storage services (OneDrive, Google Drive, Dropbox, etc.).  It would be nice if the Media feature could be expanded and/or an additional similar feature look at for files.

Thanks for the outstanding product that you have to-date.

**Comment by brianhyder** [comment]
The media service supports this kind of behavior.  Today there are a variety of file types (images, videos, audio, pdf) that are supported.  The supported types are derived from the mime types that are supported by our various media renderers.  Our blog post on [Media Management](https://pencilblue.org/article/media-renderers) covers the basics on how to extend the platform to provide support for more file types.  

Additionally, we support the ability to link to items as well as upload.  The platform requires that a renderer be registered so that the platform knows how to render the content in the link (this could be as simple as an anchor tag).  

We are always happy to look at PRs for MediaRenderers as they help us expand our file support. If you have additional questions just let us know!

**Comment by thcase** [comment]
Brian,
Thank you for the response. Is this a configuration issue?  I tried yesterday on my dev instance of a site I am working on and the pdf would not upload. In the media manager, after I selected the pdf (small one), the file never uploaded and The screen was left with the choose or drag file modal popup form. 

Thanks,
Tom

**Comment by markbaird** [comment]
That sounds like some sort of error occurred while uploading the file. I would set the log level to `silly` and try again, watching the server log for errors.

**Comment by brianhyder** [comment]
I was wrong about which version PDF support was included in.  0.4.1 does NOT include PDF support.  The upcoming release for 0.5.0 does include PDF support.  This branch provides a lot of new features and would be the branch I would use for any platform evaluations.

**Comment by thcase** [comment]
Thanks Mark. I will try that and see what (if anything) gets logged. 

Tom
