### ISSUE TITLE
[0.5.0] Theme Setting returns 404 on sub-sites

### ISSUE THREAD

**Issue by amirsaber** [pencilblue/pencilblue#836]
In 0.5.0, when I go on theme and click on settings of a theme(sample for example) it return 404 page. Is it a known bug?

**Comment by amirsaber** [comment]
It only happens on theme settings on a created site, not on the global. For the same plugin, Theme settings and Plugin settings works fine on global, but Theme settings return 404 on a created site.

**Comment by blakecallens** [comment]
@kylebechtel77 would your team be able to take a look at this?

**Comment by cchatham** [comment]
@blakecallens @brianhyder we are looking into this. @btidwell is looking

**Comment by blakecallens** [comment]
Much appreciated.

**Comment by amirsaber** [comment]
I just noticed that in simple_layered_service.js line 61 return null in case that instance.services[i] is ThemeSettingService and returns correct settings when instance.services[i] is PluginSettingService.

**Comment by btidwell** [comment]
I have found the issue.  In pluginService.js line 616 is using standard pb.DAO() without any site context.  This occurs on plugin install when we call "resetThemeSettings()". So it's saving the settings to the global scope.  As a result the controller for the theme settings page responds with a 404 because theme settings are null.

**Comment by blakecallens** [comment]
Thanks @btidwell!
