### ISSUE TITLE
[0.5.0] Scalability concerns around plugin initialization in multi-tenancy mode

### ISSUE THREAD

**Issue by andparker** [pencilblue/pencilblue#837]
Hey guys. We are noticing that for roughly 30 sites it is taking 1sec 21ms, and increasing per site, for plugin initialization (not including dependency downloads). We are concerned this might translate into minutes once we scale up to 3000+ sites.

We have already been looking into it—but not as much as we would like—and could really use your help and advice on how we could optimize this task. Mind taking a look when you have some time?

Also, sometime this week or the next, Ben is going to run some tests that would mimic how our system would perform close to that number of sites. I will post back his results once he is finished.  

Thanks

**Comment by blakecallens** [comment]
Is increasing the number of nodes in the cluster adding to things?

**Comment by andparker** [comment]
I'm not 100% sure about that.

@btidwell What do you think?

**Comment by blakecallens** [comment]
While you guys are looking into this, would you mind also looking at #836?

**Comment by cchatham** [comment]
@blakecallens we are looking into that issue

**Comment by btidwell** [comment]
Yes.  It definitely slows down a noticeable amount when adding workers to the cluster.

**Comment by blakecallens** [comment]
Ok, good to know. I'm trying to triage as much as I can for @brianhyder, before he jumps in.

**Comment by brianhyder** [comment]
Hey guys,  sorry for the delayed response.  I'd like to ask a couple of questions to get a better idea of where the bottle neck is:

1. In your setup will each site have its own plugin/theme?
2. About how many plugins are being initialized?
3. Can you do a run with multiple workers with log level "silly" so we can look at log output timestamps to help identify the bottleneck. 

Initial impressions without diving in is that the plugins are initialized in series.  Additionally, on startup, the process ensures that each plugin to be initialized has the necessary dependencies.   My guess is that initializing the plugins in series is the main bottleneck.  Specifically, the dependency check is time consuming because it must load each dependency package's package.json file is available.  In the event that we need to install dependencies (as we would need most likely on an elastic instance) then we have to wait on NPM to response.  Plugins are initialized in series because the last time I checked the npm module was not implemented in such a way that it can be run in parallel.  Getting a look at the logs will greatly help us identify where the bottle neck is occurring.

**Comment by brianhyder** [comment]
Looking at the implementation it also appears that plugins are initiallized based on querying the plugin collection.  Since plugin documents are now site specific there is most likely a lot of plugins being loaded multiple times unnecessarily.  This includes the dependency check.  Depending on the number of plugin instances that come back from that "get all" query we could probably optimize by creating an aggregation of the distinct plugins and just track the sites that they should be initialized for.

**Comment by cchatham** [comment]
@brianhyder @btidwell Ben is still looking into the exact issue you describe. We fixed the initial bottleneck of npm install on every plugin. We moved a lot of our dependancies out to our package.json. Plugin initialization was the next bottleneck as you mention with it running in series. 

Ben, can you give Brian an update on Monday?

**Comment by btidwell** [comment]
@brianhyder @blakecallens  I just went through the initPlugin function in PluginService and I identified sever steps in the process that should only be executed once.  This includes details loading, dependency checking, service loading, controller path loading, etc.  I just finished implementing a solution (probably not the best solution) that will use a static variable to "cache" a plugin so that it can be reused when building routes, setting available services, etc for each site.  I am about to deploy it into our environment to see what the improvement is (I ran a simulation against 6000 plugin installs (our typical 3 plugin per site setup for 2000 sites) and it loads anywhere from 17 to 20 seconds down from around 40 seconds. 

Also, one other thing to note, the dependency check uses whatever is stored in the DB.  I overwrote the plugin.dependencies field to use what is stored in details.json.  We get version mismatches every time we upgrade a dependency for a plugin.  Furthermore, we noticed that the node_modules folder under the application root is not checked.  I added a waterfall to first check node_modules in the plugin directory, then check from the application root.  We try to keep all of our dependencies system wide consistent by using the package.json file in pencilblue.  

What do you think of this approach?  I can create a pull request after verifying the solution in our environment to see what you think.

**Comment by brianhyder** [comment]
I think you're on the right track.  This is probably one of those things we'll have to iterate on a few times to find what is optimal.  Feel free to submit the PR or I can take a look at the commit you've got into your fork.  Either one is fine.  Ideally, I'd love to see us get down to the 5-10 second range. If you check the main node_modules directory can you please verify that the ```PluginService.require``` function also checks that location as a backup to looking at the plugin's node_modules directory first?  

The main things I'd like to address:
* Dependency checks for same plugin but for different sites.  Not much point in doing this.
* Using the ```npm install``` command in parallel.

**Comment by cchatham** [comment]
@btidwell Is our solution ready to be pulled into the 0.5.0 branch?

**Comment by btidwell** [comment]
@cchatham Getting close.  I'm actually running a few tests to make sure I didn't overlook something.

**Comment by brianhyder** [comment]
That's awesome guys.  I looked into calling NPM in parallel.  The package is still a singleton per process.  There is no way to make the requests in parallel for different plugins.

**Comment by brianhyder** [comment]
Whenever the PR comes in I will start looking over it.

**Comment by btidwell** [comment]
Pull request has been submitted.  There are further improvements that probably could be made but this is a start.  https://github.com/pencilblue/pencilblue/pull/886
