### ISSUE TITLE
https error

### ISSUE THREAD

**Issue by MarinAngelo** [pencilblue/pencilblue#869]
I successfully installed pencilblue localy and than deployed it ot heroku/compose. Localy everything worked perfect, but on heroku when adding a new article a receive the following error message in the console and I con not create an article:

Mixed Content: The page at 'https://mahlzeiten.herokuapp.com/admin/content/articles/new' was loaded over HTTPS, but requested an insecure script 'http://rangy.googlecode.com/svn/trunk/currentrelease/rangy-core.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by brianhyder** [comment]
Thank you for reporting. This sounds like a mistake on our part. In the
site settings section of pencilblue look for the libraries section. It
should list all the third party libraries. You can update the rangy url to
be https instead of http. That should correct the issue.  After updating
you may need to restart the dyno.

Let us know of that gets you around the issue and we'll look into what the
default is in source.

The other option is to use our bower support. This can be switched on in
the same screen mentioned above but will need bower install to be ran on
the dyno or before the package is created and uploaded to heroku.

**Comment by brianhyder** [comment]
Confirmed as a bug.  When new client side dependencies are added to the "library" defaults they must support http and https protocols.  Rangy was added to libraries.js as ```http``` only.  There is a work around so we will correct this as part of the 0.5.0 release

**Comment by MarinAngelo** [comment]
that works, thank's
