### ISSUE TITLE
Easy Extensiblilty of Core Objects

### ISSUE THREAD

**Issue by JahlomP** [pencilblue/pencilblue#937]
I was wondering if a customize section could be added to the core content objects like article, navigation and the others. This will be used by users to extend the core objects without creating new objects.

For example, if someone wants his article object to have a video and  image banner fields, this feature should let the user  quickly add new field definitions just like custom objects but this time it is the core object he or she is updating not creating a new object altogether.

This will reduce the pain of programatically doing so or trying to find a way to display it on a page.

I hope I am making sense.

**Comment by Chris-Satchell** [comment]
I second that suggestion. Currently I´m having to use a custom object to assign media to an article (not talking about images in the article itself), which works well, but having it nicely embedded into the core would be awesome.

**Comment by brianhyder** [comment]
We are moving in a direction that supports this functionality.  Services, such as ArticleServiceV2 and PageService, that extend BaseObjectService allow for registering for events.  We don't have much documentation on this (that is on me).  

In the example of wanting to add a field to the articles collection one would do the following:

* Register for the ```format``` event.  It allows you to sanitize fields and format them to populate the object that will be persisted to the DB.  Example [here](https://github.com/pencilblue/pencilblue/blob/master/include/service/entities/topic_service.js#L117).
* Register for the ```merge``` event.  It allows you to ensure that your new field gets added to the object that will be persisted to the DB.  
* Register for the ```validate``` event.  It allows you to validate your new field before it gets persisted to the DB.  

There are two ways to register for events.  The first is to register for the event with a specific type: ```"article" +"." + BaseObjectService.FORMAT```.  The second is to register for an event type for all objects, ```BaseObjectService.FORMAT```.

You should register for these events in your plugin's ```onStartupWithContext```.  It replaces the deprecated ```onStartup``` function in your main module file.  Both still work but you might want to upgrade if you start tinkering with multi-site.

The above takes care of the back end changes.  In your plugin you will still need to override the form that is used for collection you would like to add to.  In your case, the article form.  

Let me know if there is anything I can clarify for you guys.  I'm hoping to put some more detailed documentation together for you soon.  In the meantime, the source is pretty well documented for BaseObjectService.  You can look at the source directly or the [API Reference](https://pencilblue.github.io).  The ArticleServiceV2, PageService, TopicService, and UserService all extend BaseObjectService.  You can look at their implementations to get a since of how to register for events and the data available to each callback.

**Comment by JahlomP** [comment]
OK. Thanks.
