### ISSUE TITLE
100% CPU on Ctrl + C

### ISSUE THREAD

**Issue by almereyda** [pencilblue/pencilblue#952]
When started with `pbctrl start` the Shutdown signal yields 100% CPU utilization, which does not happen when instanciated with `node pencilblue`.

This is therefore more probably an issue of https://github.com/pencilblue/pencilblue-cli?

**Comment by brianhyder** [comment]
There are known issues with the CLI.  We suggest that users use the following in dev environments:

* node pencilblue.js
* nodemon pencilblue.js

In production we encourage users to use a scaled managed environment. If managing it yourself then using forever.js is a good way to go. 

We track all issues with the CLI here: https://github.com/pencilblue/pencilblue-cli/issues

The reality is that the CLI get a lot less attention than the platform itself due to the number of resources we have and the demand for features.

Thank you for reporting the issue!
